#!/usr/bin/env bash
export PHP_VERSION_MIN="50400"
export PHP_VERSION_MAX="50499"
export COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/di:~2.3.0"
export COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/utils:~2.3.0"
export COMPOSER_REQUIRE="$COMPOSER_REQUIRE dibi/dibi:~3.0"
export COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/dbal:~2.0"
export COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/orm:~2.0"
export COMPOSER_REQUIRE="$COMPOSER_REQUIRE nextras/dbal:~1.0"
