#!/usr/bin/env bash
PHP_VERSION_MIN="50500"
PHP_VERSION_MAX="70199"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/di:~2.3.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/utils:~2.3.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE dibi/dibi:~3.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/dbal:~2.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/orm:~2.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE nextras/dbal:~2.0"
