#!/usr/bin/env bash
export PHP_VERSION_MIN="50600"
export PHP_VERSION_MAX="70099"
export COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/di:~2.4.0"
export COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/utils:~2.4.0"
export COMPOSER_REQUIRE="$COMPOSER_REQUIRE dibi/dibi:~3.0"
export COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/dbal:~2.0"
export COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/orm:~2.0"
export COMPOSER_REQUIRE="$COMPOSER_REQUIRE nextras/dbal:~2.0"
