#!/usr/bin/env bash
PHP_VERSION_MIN="80000"
PHP_VERSION_MAX="80099"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/di:2.4.*"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE dibi/dibi:*"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/dbal:^2.13|^3.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/orm:^2.11"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/cache:^1.11"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/console:*"
