#!/usr/bin/env bash
PHP_VERSION_MIN="80500"
PHP_VERSION_MAX="80599"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/dbal:^4.3.4"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/tester:dev-master"
DBAL="doctrine"
