#!/usr/bin/env bash
PHP_VERSION_MIN="70100"
PHP_VERSION_MAX="70399"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/database:~3.0@alpha"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/caching:~3.0@beta"
DBAL="nette"
