#!/usr/bin/env bash
PHP_VERSION_MIN="70100"
PHP_VERSION_MAX="70499"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/database:~3.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/caching:~3.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/tester:~2.3"
DBAL="nette"
