#!/usr/bin/env bash
PHP_VERSION_MIN="70300"
PHP_VERSION_MAX="70499"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/dbal:~2.5"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/orm:~2.6.3"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/doctrine-bundle:~1.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/config:~3.4"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/console:~3.4"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/dependency-injection:~3.4"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/doctrine-bridge:~3.4"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/framework-bundle:~3.4"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/http-kernel:~3.4"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/yaml:~3.4"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE nette/tester:~2.3"

DBAL='doctrine'
