#!/usr/bin/env bash
PHP_VERSION_MIN="80100"
PHP_VERSION_MAX="80599"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/framework-bundle:6.4.*"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/yaml:6.4.*"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/doctrine-bundle:^2.6"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/dbal:^3.3"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/orm:^2.11"
DBAL='doctrine'
