#!/usr/bin/env bash
PHP_VERSION_MIN="50500"
PHP_VERSION_MAX="70299"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/dbal:~2.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/orm:~2.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/doctrine-bundle"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/config:~3.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/console:~3.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/dependency-injection:~3.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/http-kernel:~3.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/yaml:~3.0"
DBAL='doctrine'
