#!/usr/bin/env bash
PHP_VERSION_MIN="70100"
PHP_VERSION_MAX="70299"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/dbal:~2.5"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/orm:~2.5"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE doctrine/doctrine-bundle:~2.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/config:~4.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/console:~4.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/dependency-injection:~4.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/doctrine-bridge:~4.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/framework-bundle:~4.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/http-kernel:~4.0"
COMPOSER_REQUIRE="$COMPOSER_REQUIRE symfony/yaml:~4.0"
DBAL='doctrine'
