name: QA

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master
      - v*

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']

    name: PHP ${{ matrix.php }}

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nextras_migrations_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql:5.6
        env:
          MYSQL_DATABASE: nextras_migrations_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, ctype, mysqli, pgsql, pdo_mysql, pdo_pgsql
          coverage: none

      - name: Prepare Env
        run: |
          cp ./tests/drivers.sample.ini ./tests/drivers.ini
          composer install --no-interaction --no-progress

      - run: tests/run-unit.sh
      - run: tests/run-integration.sh
